### PR TITLE
Made code PEP8 compliant

### PR DESCRIPTION
**Pull request by IamRaviTejaG-zz**
Fixes issue #1

### CODE REVIEW

**Review by palash25 — COMMENTED** [review]
Looks much better now. @IamRaviTejaG did you run coala or did it manually?

**Comment by IamRaviTejaG-zz** [comment]
@palash25 Manually. 😅

**Comment by palash25** [comment]
can you run coala? Its a big diff and I would trust a linter more than you :wink: 

But its okay if you don't want to we can merge it for now and run coala later

**Comment by IamRaviTejaG-zz** [comment]
@palash25 I did check it on an online PEP8 linter after making the changes. I'm fine with coala too if you suggest.

**Comment by palash25** [comment]
can you give the bot a try on slack and see if it still working since we don't have tests right now ? @IamRaviTejaG

**Comment by IamRaviTejaG-zz** [comment]
@palash25 Sure!

**Pull request merged**
